# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/manual-segmentation-preprocessing',
                'doc_host': 'https://mone27.github.io',
                'git_url': 'https://github.com/mone27/manual-segmentation-preprocessing',
                'lib_path': 'man_seg_preproc'},
  'syms': { 'man_seg_preproc.core': {'man_seg_preproc.core.foo': ('core.html#foo', 'man_seg_preproc/core.py')},
            'man_seg_preproc.utils': {'man_seg_preproc.utils.run_pdal': ('utils.html#run_pdal', 'man_seg_preproc/utils.py')}}}
