# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb.

# %% auto 0
__all__ = ['url', 'weights_dir', 'dst', 'model_config', 'pipeline_config', 'model', 'pipeline', 'cloud_paths', 'dir_leaves',
           'dir_wood', 'read_cloud', 'LWTransformerBatch', 'LWBatcher', 'LWPointTransformer', 'LWSemanticSegmentation',
           'post_processing', 'save_cloud', 'process_cloud', 'process_all']

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 4
from pyprojroot import here
import requests
from pathlib import Path
import zipfile
import laspy
import numpy as np

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 5
url = "https://zenodo.org/records/13767795/files/model_weights.zip?download=1"
weights_dir = here("data/weights")
dst = weights_dir / "model_weights.zip"

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 6
if not dst.exists():
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(dst, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)

if not weights_dir.exists():
    weights_dir.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(dst, "r") as z:
        z.extractall(weights_dir)

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 7
def read_cloud(path):
    las = laspy.read(path)
    return {
        'point': las.xyz,
        'point_orig': np.stack((las.X, las.Y, las.Z), axis=-1), # UNSCALEd points to avoid float precision issues
        'header': las.header
    }

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 12
import open3d.ml.torch as ml3d
import torch
from sklearn.neighbors import KDTree

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 13
class LWTransformerBatch:
    def __init__(self, batches):
        pc = []
        point_inds = []
        splits = [0]

        for batch in batches:
            data = batch['data']
            pc.append(data['point'])
            point_inds.append(data['point_inds'])
            splits.append(splits[-1] + data['point'].shape[0])

        self.point = torch.cat(pc, 0)  
        self.point_inds = torch.cat(point_inds, 0)
        self.row_splits = torch.LongTensor(splits)
        self.feat = [] # expected by the model forward

    def pin_memory(self):
        self.point = self.point.pin_memory()
        return self
    
    def to(self, device):
        self.point = self.point.to(device)

class LWBatcher(ml3d.dataloaders.ConcatBatcher):
    def collate_fn(self, batches):
        return {'data': LWTransformerBatch(batches), 'attr': {}}

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 14
class LWPointTransformer(ml3d.models.PointTransformer):
    def transform(self, data, attr):
        pc = data['point'].copy()
        label = data['label'].copy()
        tree = data['search_tree']

        # Select num_points from whole cloud (randomly pick center and take num_point nearest neighbours) 
        pc, selected_idxs, center_point = self.trans_point_sampler(
            pc=pc,
            feat=None,
            label=label,
            search_tree=tree,
            num_points=self.cfg.max_voxels
        )
        label = label[selected_idxs]
        # Apply augmentations
        augment_cfg = self.cfg.get('augment', {}).copy()
        val_augment_cfg = {}
        if 'recenter' in augment_cfg:
            val_augment_cfg['recenter'] = augment_cfg.pop('recenter')
        if 'normalize' in augment_cfg:
            val_augment_cfg['normalize'] = augment_cfg.pop('normalize')

        pc, _, label = self.augmenter.augment(pc, None, None, val_augment_cfg)

        inputs = dict()
        inputs['point'] = torch.from_numpy(pc).to(torch.float32)
        inputs['point_inds'] = torch.from_numpy(selected_idxs).to(torch.int64)

        return inputs

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 16
from torch.utils.data import DataLoader
from tqdm.auto import tqdm

class LWSemanticSegmentation(ml3d.pipelines.SemanticSegmentation):
    def run_inference(self, data):
        """Run inference on given data.

        Args:
            data: A raw data.

        Returns:
            Returns the inference results.
        """
        cfg = self.cfg
        model = self.model
        device = self.device

        model.to(device)
        model.device = device
        model.eval()

        batcher = LWBatcher(self.device, "LWPointTransformer")
        infer_dataset = ml3d.datasets.InferenceDummySplit(data)
        self.dataset_split = infer_dataset
        infer_sampler = infer_dataset.sampler
        infer_split = ml3d.dataloaders.TorchDataloader(dataset=infer_dataset,
                                      preprocess=model.preprocess,
                                      transform=model.transform,
                                      sampler=infer_sampler,
                                      use_cache=False)
        infer_loader = DataLoader(infer_split,
                                  batch_size=cfg.batch_size,
                                  sampler=ml3d.dataloaders.get_sampler(infer_sampler),
                                  collate_fn=batcher.collate_fn)

        model.trans_point_sampler = infer_sampler.get_point_sampler()
        # self.curr_cloud_id = -1
        # self.test_probs = []
        # self.ori_test_probs = []
        # self.ori_test_labels = []
        with torch.no_grad():
            inputs = next(iter(infer_loader))
            inputs['data'].to(device)
            return model(inputs['data'])
        


    #         for inputs in infer_loader:
    #             inputs['data'].to(device)
    #             results = model(inputs['data'])
    #             self.update_tests(infer_sampler, inputs, results)

    #     inference_result = {
    #         'predict_labels': self.ori_test_labels.pop(),
    #         'predict_scores': self.ori_test_probs.pop()
    #     }

    #     return inference_result

    
    # def update_tests(self, sampler, inputs, results):
    #     """Update tests using sampler, inputs, and results."""
    #     split = sampler.split # split = 'test'
    #     end_threshold = 0.5
    #     if self.curr_cloud_id != sampler.cloud_id:
    #         self.curr_cloud_id = sampler.cloud_id
    #         num_points = sampler.possibilities[sampler.cloud_id].shape[0]
    #         self.pbar = tqdm(
    #             total=num_points,
    #             desc="{} {}/{}".format(split, self.curr_cloud_id, len(sampler.dataset))
    #         )
    #         self.pbar_update = 0
    #         self.test_probs.append(np.zeros(shape=[num_points, self.model.cfg.num_classes], dtype=np.float16))
    #         self.complete_infer = False

    #     this_possiblility = sampler.possibilities[sampler.cloud_id]
    #     self.pbar.update(this_possiblility[this_possiblility > end_threshold].shape[0] - self.pbar_update)
    #     self.pbar_update = this_possiblility[this_possiblility > end_threshold].shape[0]

    #     self.test_probs[self.curr_cloud_id] = self.model.update_probs(
    #         inputs,
    #         results,
        #     self.test_probs[self.curr_cloud_id],
        # )

        # # When all predictions are made
        # if (split in ['test'] and
        #         this_possiblility[this_possiblility > end_threshold].shape[0]
        #         == this_possiblility.shape[0]):

        #     proj_inds = self.model.preprocess(
        #         self.dataset_split.get_data(self.curr_cloud_id),
        #         {'split': split},
        #     ).get('proj_inds', None)
            
        #     if proj_inds is None:
        #         proj_inds = np.arange(self.test_probs[self.curr_cloud_id].shape[0])

        #     test_labels = np.argmax(self.test_probs[self.curr_cloud_id][proj_inds], 1)

        #     self.ori_test_probs.append(self.test_probs[self.curr_cloud_id][proj_inds])
        #     self.ori_test_labels.append(test_labels)
        #     self.complete_infer = True

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 19
model_config = {'name': 'PointTransformer',
 'batcher': 'ConcatBatcher',
 'ckpt_path': str(here("data/weights/model_weights/weights_pointtransformer.pth")),
 'is_resume': False,
 'in_channels': 3,
 'blocks': [2, 3, 4, 6, 3],
 'num_classes': 2,
 'voxel_size': 0.02,
#  'max_voxels': 2_000_000,
 'max_voxels': 10_000, # for testing
 'ignored_label_inds': [],
 'augment': {
    'recenter' : {'dim': [0, 1, 2]},
    'normalize' : {},
    'rotate':
      {'method': 'vertical'},
    'scale': {
      'min_s': 0.9,
      'max_s': 1.1
    }
 }
}

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 20
pipeline_config = {
'name': 'SemanticSegmentation',
 'device': 'cuda:0',
 'num_workers': 16,
 'batch_size': 1,
}

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 21
model = LWPointTransformer(**model_config)
pipeline = LWSemanticSegmentation(model, **pipeline_config)

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 22
pipeline.load_ckpt(here("data/weights/model_weights/weights_pointtransformer.pth"))

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 32
def post_processing(pred, cloud, threshold) -> tuple[np.ndarray, np.ndarray]:
    probs = torch.nn.functional.softmax(pred, dim=-1).cpu().data.numpy()
    # conver to original points
    proj_inds = model.preprocess(cloud, attr={'split': 'test'})['proj_inds']
    probs_points = probs[proj_inds]
    # softmax and threshold
    is_wood = probs_points[:, 0] > threshold
    # return the unscaled dimensions not the input
    return (cloud['point_orig'][is_wood], cloud['point_orig'][~is_wood])

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 35
def save_cloud(cloud: np.ndarray, name, header):
    las = laspy.LasData(header)
    las.X = cloud[:, 0]
    las.Y = cloud[:, 1]
    las.Z = cloud[:, 2]
    las.write(name)

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 37
import fastcore.xtras # ls
from tqdm.auto import tqdm

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 38
cloud_paths = here("data/1_tiled/").ls()
cloud_paths

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 40
dir_leaves = here("data/2_lw_segmented/leaves/")
dir_wood = here("data/2_lw_segmented/wood/")
dir_wood.mkdir(parents=True, exist_ok=True)
dir_leaves.mkdir(parents=True, exist_ok=True)

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 41
def process_cloud(path):
    cloud = read_cloud(path)
    predictions = pipeline.run_inference(cloud)
    wood, leaves = post_processing(predictions, cloud, 0.75)
    save_cloud(leaves, dir_leaves / Path(path).name, cloud['header'])
    save_cloud(wood, dir_wood / Path(path).name, cloud['header'])

# %% ../nbs/lw_segmentation/01_leaf-wood_segmentation.ipynb 50
def process_all(paths):
    for path in tqdm(paths):
        process_cloud(path)
