# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_pretty_names.ipynb.

# %% auto 0
__all__ = ['names', 'extract_cell_info', 'get_nth_genus', 'get_n_genera', 'add_hilbert_index', 'get_cell_to_genus',
           'rename_trees', 'rename_files', 'make_grid', 'get_pretty_names']

# %% ../nbs/01_pretty_names.ipynb 2
import geopandas as gpd
import pandas as pd
from pyprojroot import here
import string
from hilbertcurve.hilbertcurve import HilbertCurve
from pathlib import Path
from shapely.geometry import box
import shutil

# %% ../nbs/01_pretty_names.ipynb 5
def extract_cell_info(df):
    extract_cell_id_re = r'(\d{6}_\d{7})'
    df['cell_id'] = df.GIS_ID.str.extract(extract_cell_id_re).squeeze()
    df['grid_x'] = df['cell_id'].str.split('_').str[0].astype(int)
    df['grid_y'] = df['cell_id'].str.split('_').str[1].astype(int)
    return df

# %% ../nbs/01_pretty_names.ipynb 9
names = pd.read_csv(here("assets/short_genus_names.csv"))
names["name_lower"] = names["unit_name1"].str.lower()


# %% ../nbs/01_pretty_names.ipynb 12
def get_nth_genus(n) -> str | None:
    char_idx = n // 25
    letter_idx = n % 25
    sort_ascending = not bool(char_idx % 2) # to increase variability sort the 1st char in ascending order, the second in desceding and so on
    letter = string.ascii_lowercase[letter_idx]
    match = names.query(f"name_lower.str[{char_idx}] == '{letter}'")
    maybe_item =  match.sort_values('name_lower', ascending=sort_ascending).head(1).unit_name1
    return maybe_item.item() if len(maybe_item) > 0 else None

# %% ../nbs/01_pretty_names.ipynb 14
def get_n_genera(n: int) -> set[str]:
    selected = set()
    i = 0
    while len(selected) < n:
        item = get_nth_genus(i)
        if item is not None: selected.add(item)
        i += 1
    return selected

# %% ../nbs/01_pretty_names.ipynb 18
def add_hilbert_index(df) -> pd.DataFrame:
    df['grid_x_norm'] = df['grid_x'] - df['grid_x'].min()
    df['grid_y_norm'] = df['grid_y'] - df['grid_y'].min()
    hilbert = HilbertCurve(8, 2)
    df['hilbert_dist'] = df.apply(lambda row: hilbert.distance_from_point([row['grid_x_norm'], row['grid_y_norm']]), axis=1)
    df.drop(columns=["grid_x_norm", "grid_y_norm"])
    return df

# %% ../nbs/01_pretty_names.ipynb 21
def get_cell_to_genus(df, selected_genera) -> dict[str, str]:
    cell_order = df.groupby('cell_id')['hilbert_dist'].first().sort_values()
    return dict(zip(cell_order.index, sorted(selected_genera)))

# %% ../nbs/01_pretty_names.ipynb 23
def rename_trees(df, cell_to_genus: dict[str, str]) -> pd.DataFrame:
    df['suffix']  = df['GIS_ID'].str.extract(r'\d{6}_\d{7}_(.+)')
    df['pretty_name'] = df['cell_id'].map(cell_to_genus) + '_' + df['suffix']
    return df

# %% ../nbs/01_pretty_names.ipynb 26
def rename_files(df, start_folder: Path, target_folder: Path, dry_run=False):
    name_map = dict(zip(df['GIS_ID'], df['pretty_name']))
    las_files = list(start_folder.glob('*.las'))
    for f in las_files:
        stem = f.stem
        if stem in name_map:
            new_name = target_folder / f"{name_map[stem]}.las"
            print(f"{f.name} -> {new_name.name}")
            if not dry_run: shutil.copy(f, new_name)
        else: print(f"Skipping {f.name} (not in map)")

# %% ../nbs/01_pretty_names.ipynb 28
def make_grid(df, cell_to_genus, cell_size=10):
    grid = df[['cell_id', 'grid_x', 'grid_y']].drop_duplicates().copy()
    grid['pretty_name'] = grid['cell_id'].map(cell_to_genus)
    grid['geometry'] = grid.apply( lambda row: box(row['grid_x'], row['grid_y'], row['grid_x'] + cell_size, row['grid_y'] + cell_size),
            axis=1
        )
    grid = gpd.GeoDataFrame(grid, crs = df.crs)
    return grid

# %% ../nbs/01_pretty_names.ipynb 30
def get_pretty_names(crowns_path: Path) -> tuple[pd.DataFrame, dict[str, str]]:
    df = gpd.read_file(crowns_path)
    df = extract_cell_info(df)
    selected_genera = get_n_genera(df['cell_id'].nunique())
    df = add_hilbert_index(df)
    cell_to_genus = get_cell_to_genus(df, selected_genera)
    df = rename_trees(df, cell_to_genus)
    return df, cell_to_genus
