# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/99_utils.ipynb.

# %% auto 0
__all__ = ['run_pdal']

# %% ../nbs/99_utils.ipynb 2
from pdal import Pipeline
import subprocess


# %% ../nbs/99_utils.ipynb 3
def run_pdal(pipeline: Pipeline, pipe_name="pdal", args=[]):
    with open(f"pipeline_{pipe_name}.json", "w") as f:
        f.write(pipeline.toJSON())
    cmd = ["pdal", "pipeline", f"pipeline_{pipe_name}.json"]
    cmd.extend(args) # overwrites pipeline attrs, for example ["--writer.las.filename", "new_name"]
    subprocess.run(cmd, check=True)
